Update build_binary.yml

diff --git a/.github/workflows/build_binary.yml b/.github/workflows/build_binary.yml
--- a/.github/workflows/build_binary.yml
+++ b/.github/workflows/build_binary.yml
@@ -97,24 +97,29 @@ jobs:
       - name: Build Windows Binary
         run: |
           echo "Building the Windows binary"
-      
+          
           # Ensure artifacts directory exists
-          mkdir artifacts
-      
+          mkdir -p artifacts
+          
           # Debug the environment and library paths
           echo "Verifying environment paths:"
           echo $PATH
+          
           echo "Verifying presence of GCC:"
           where gcc || echo "GCC not found"
+      
           echo "Verifying MinGW library path:"
           if [ -d "C:/ProgramData/chocolatey/lib/mingw/tools/install" ]; then
-            echo "MinGW directory found."
+            echo "MinGW directory found at C:/ProgramData/chocolatey/lib/mingw/tools/install."
             dir C:/ProgramData/chocolatey/lib/mingw/tools/install
+          elif [ -d "C:/mingw64" ]; then
+            echo "MinGW directory found at C:/mingw64."
+            dir C:/mingw64
           else
-            echo "MinGW directory not found"
+            echo "MinGW directory not found in expected paths."
             exit 1
           fi
-      
+          
           # Attempt to build the package binary
           echo "Attempting to build the package binary:"
           Rscript -e "devtools::build(binary = TRUE, path = 'artifacts')" || ( \
@@ -133,11 +138,19 @@ jobs:
             fi && \
             exit 1 \
           )
-
+          
           # Verify artifacts
           echo "Checking artifacts directory:"
           dir artifacts
-        shell: bash
+        shell: C:\rtools44\usr\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
+        env:
+          OS_TYPE: windows
+          _R_INSTALL_TIME_PATCHES_: no
+          R_LIBS_USER: D:\a\_temp\Library
+          TZ: UTC
+          _R_CHECK_SYSTEM_CLOCK_: FALSE
+          NOT_CRAN: true
+
 
 
       # Step 9: Debug Artifacts Directory
